data_root:
  # KITTI sequences root
  data_root_folder: "/media/vision/Data0/DataSets/kitti/dataset/sequences/"
  # data_root_folder: "/home/mjy/datasets/overlapnet_datasets/OverlapNet/kitti/dataset_full/"
  # KITTI sequence 02 velodyne
  valid_scan_folder: "/media/vision/Data0/DataSets/kitti/dataset/sequences/02/velodyne"
  # KITTI sequence 02 computed overlaps
  gt_valid_folder: "/media/vision/Data0/DataSets/kitti/dataset/sequences/computed_overlap/"

demo1_config:
  # calibration file from KITTI 00
  calib_file: "/media/vision/Data0/DataSets/kitti/dataset/sequences/00/calib.txt"
  # pose file from KITTI 00
  poses_file: "/media/vision/Data0/DataSets/kitti/dataset/poses/00.txt"
  # pretrained model
  test_weights: "../checkpoints/pretrained/pretrained_overlap_transformer.pth.tar"

training_config:
  # KITTI sequences for training
  training_seqs: ["03", "04", "05","06", "07", "08", "09"]

test_config:
  # KITTI sequence 00 for evaluation
  test_seqs: ["00"]
  # pretrained model
  test_weights: "../checkpoints/pretrained/pretrained_overlap_transformer.pth.tar"
  # ground truth
  gt_file: "/media/vision/Data0/DataSets/kitti/dataset/loop_gt_seq00_0.3overlap_inactive.npz"

viz_config:
  # calibration file from KITTI 00
  calib_file: "/media/vision/Data0/DataSets/kitti/dataset/sequences/00/calib.txt"
  # pose file from KITTI 00
  poses_file: "/media/vision/Data0/DataSets/kitti/dataset/poses/00.txt"
  # covariance file from SUMA++ on KITTI 00
  cov_file: "/media/vision/Data0/DataSets/kitti/dataset/covariance_2nd.txt"
